export default {
  SELECT_DATE: 'SELECT_DATE',
  SELECT_SEAT: 'SELECT_SEAT',
  SELECT_TICKET: 'SELECT_TICKET',
  SELECT_END_POINT: 'SELECT_END_POINT',
  SELECT_START_TIME: 'SELECT_START_TIME',
  SELECT_DROP_POINT: 'SELECT_DROP_POINT',
  SELECT_START_POINT: 'SELECT_START_POINT',
};
