export default {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',

  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  AUTH_REGISTER_ERROR: 'AUTH_REGISTER_ERROR',

  AUTH_REGISTER_VERIFY_CODE: 'AUTH_REGISTER_VERIFY_CODE',
  AUTH_REGISTER_VERIFY_CODE_SUCCESS: 'AUTH_REGISTER_VERIFY_CODE_SUCCESS',
  AUTH_REGISTER_VERIFY_CODE_ERROR: 'AUTH_REGISTER_VERIFY_CODE_ERROR',

  AUTH_CHECK_ASYNC_STORAGE: 'AUTH_CHECK_ASYNC_STORAGE',
  AUTH_CHECK_ASYNC_STORAGE_DONE: 'AUTH_CHECK_ASYNC_STORAGE_DONE',

  AUTH_LOGOUT_HANDLING: 'AUTH_LOGOUT_HANDLING',
  AUTH_LOGOUT_DONE: 'AUTH_LOGOUT_DONE',

  AUTH_UPDATE_PROFILE: 'AUTH_UPDATE_PROFILE',
  AUTH_UPDATE_PROFILE_FAIL: 'AUTH_UPDATE_PROFILE_FAIL',
  AUTH_UPDATE_PROFILE_SUCCESS: 'AUTH_UPDATE_PROFILE_SUCCESS',

  AUTH_UPDATE_PASSWORD: 'AUTH_UPDATE_PASSWORD',
  AUTH_UPDATE_PASSWORD_FAIL: 'AUTH_UPDATE_PASSWORD_FAIL',
  AUTH_UPDATE_PASSWORD_SUCCESS: 'AUTH_UPDATE_PASSWORD_SUCCESS',

};
